fix(client,server): re-enable clap default features
When default features are disabled, clap does not e.g. generate logic for
`--help` or `--version` handling. Instead it errors with the opaque error on
anything other than correct command line flags.

```
$ neqo-client --version

error: unexpected argument found
```

Instead of removing `default-features = false`, enable them individually.

See https://docs.rs/clap/latest/clap/_features/index.html for details.