ci: Only install sccache action once per workflow (#2123)
* ci: Disable sccache on Windows again

Because for some reason today, the action doesn't install:
```
Error: Error: File was unable to be removed Error: EBUSY: resource busy or locked, rmdir 'C:\hostedtoolcache\windows\sccache\0.8.1\x64'
Error: File was unable to be removed Error: EBUSY: resource busy or locked, rmdir 'C:\hostedtoolcache\windows\sccache\0.8.1\x64'
```

* Check if it's installed already

* Fix