chore: Update deps to Gecko versions
Except `itertools`, which fails with
```
cargo update -p itertools --precise 0.14.0
    Updating crates.io index
error: failed to select a version for the requirement `itertools = ">=0.10, <0.14"`
candidate versions found which didn't match: 0.14.0
location searched: crates.io index
required by package `bindgen v0.72.0`
    ... which satisfies dependency `bindgen = "^0.72"` (locked to 0.72.0) of package `neqo-crypto v0.21.0 (/Volumes/mozdrone/Users/mozdrone/Documents/Code/neqo/main/neqo-crypto)`
    ... which satisfies path dependency `neqo-crypto` (locked to 0.21.0) of package `fuzz v0.21.0 (/Volumes/mozdrone/Users/mozdrone/Documents/Code/neqo/main/fuzz)`
```